### ISSUE TITLE
Prismic query not found

### ISSUE THREAD

**Issue by mehtavishwa30** [deamme/gatsby-starter-prismic-resume#1]
Hi! 
I am building a simple Gatsby site using Prismic as CMS. So far I have successfully integrated my Prismic repository using the access token generated.
However, I cannot find the Prismic query in the GraphiQL explorer. 

Please let me know if you can tell what might be wrong. 

Thanks!

**Comment by deamme** [comment]
Do you have a repo I can take a look at?
You can also reach out to me on Twitter. https://twitter.com/deamlabs

**Comment by deamme** [comment]
Seems like the issue has been resolved.
