### ISSUE TITLE
Spans instead of a tags.

### ISSUE THREAD

**Issue by burraksumer** [deamme/gatsby-starter-prismic-resume#3]
In the video and the builded site but if you build it now, you will see that it creates spans inside a tags which is not ideal and also mess the styling up. 
I don't know what causes this, couldn't identify.

**Comment by burraksumer** [comment]
I found that it has to do with what it's getting from prismic, or how it's rendering it.
I should get a tags inside spans but its getting spans inside a tags.

`<div class="section">
    <h2>WORK EXPERIENCE</h2>
    <div>
        <p>
**<span rel="noopener" href="https://xxx.xxx" class="headline" target="_blank">
<a href="https://xxx.xxx">xxx.xxx</a>
</span>
</p>**
        <p><span class="grey">Founder | Aug, 2008 - Current</span></p>
        <p>blablabla</p>
        <ul>
            <li>list item</li>
            <li>list item</li>
            <li>list item</li>
        </ul>
        <p><a target="_blank" rel="noopener" href="xxx.xxx"><span class="headline">xxx</span></a></p>
        <p><span class="grey">Freelancer | May, 2016 - Current</span></p>
        <p>list item</p>
        <ul>
            <li>list item</li>
            <li>list item</li>
        </ul>
    </div>
</div>`

**Comment by deamme** [comment]
@burraksumer I'll take a look. Sorry for the late response, I apparently don't get these notifications.

**Comment by deamme** [comment]
@burraksumer Can't even make it build properly. Tracking the issue here https://github.com/angeloashmore/gatsby-source-prismic/issues/212

**Comment by burraksumer** [comment]
Probably has something to do with parse or mapping project and most probably it can be remapped. I don't really know about the build problem tho.

As for the spans and tags, see [here](https://cv.buraksumer.com/) to what it looks like when they are not proper but a few lines of styles has changed.

**Comment by deamme** [comment]
@burraksumer If you remove the `margin-bottom: 2rem;` on `h2` and add `display: block;` to `headline`, it should fix your problem.

**Comment by deamme** [comment]
I got my built to work and everything looks fine.

**Comment by burraksumer** [comment]
It has told to be working, so it is, I guess.

The solution is already been given two comments upwards.
